#!/bin/sh

# $Id$

if [ $# = 0 ]
then echo "usage: `basename $0` file.{icl,dcl} ... >tags" >&2
     exit 1
fi

{ echo '!_DUMMY	tags	//	;" vi:set ts=32 noet:'
  for f
  do qf="`echo \"$f\" | sed -e 's:/:\\\\/:g'`"
     sed -n -e "/^::[ 	]*\<[A-Za-z0-9_]*\>/{" \
                -e "s/^\(::[ 	]*\<\([A-Za-z0-9_]*\)\>\).*/\2	$qf	\/^\1\\\\>\//" \
                -e "s/	/\\\\t/g" \
                -e "s/\\\\t/	/" \
                -e "s/\\\\t/	/" \
                -e p \
            -e \} \
            -e "/\<[A-Za-z0-9_]*\>[ 	]*::/{" \
                -e "s/.*\(\<\([A-Za-z0-9_]*\)\>[ 	]*::\).*/\2	$qf	\/\1\//" \
                -e "s/	/\\\\t/g" \
                -e "s/\\\\t/	/" \
                -e "s/\\\\t/	/" \
                -e p \
            -e \} \
            $f
  done
} | sort
