
#define CLEAN2

#define SHORT_CLASS_NAMES
#define U_RECORD_SELECTORS 1

#define REMOVE_UNUSED_FUNCTIONS
#define OPTIMISE_STRICT_RHS_SELECTORS

#define STORE_STRICT_CALL_NODES 1
#define UNBOXED_CLOSURES 1
#undef OBSERVE_ARRAY_SELECTS_IN_PATTERN

#define ABSTRACT_OBJECT 1 /* bug fix */

#define TRANSFORM_PATTERNS_BEFORE_STRICTNESS_ANALYSIS
#define IMPORT_OBJ_AND_LIB 1

#define WRITE_DCL_MODIFICATION_TIME 1

#define STRICT_LISTS 1

#undef KARBON